format = "$directory$git_branch$character"

[directory]
style = "blue"

[git_branch]
format = " on [$branch](purple)"
style = "purple"

[character]
success_symbol = " [➜](green)"
error_symbol = " [✗](red)"
